### ISSUE TITLE
Comments*

### ISSUE THREAD

**Issue by VB10** [merthankavak/sustainable_cities#1]
Elinize saglik

- genlde file isimlednirmeleri underscore olur yani quiz_infrimation
- bir  islem yapiyorsanizmuhakkak bir sinifin elemani olsun misal citylist i CityList sinifi yapip icine listgenerator yapin
- theme kullanip daha iyi kodlayabilrisniz
- atomic widgetlari sayfalarda da dikkat edeiblriiz
- mvvm mvc gibi patternleri enteegre edip viewdan busines skodu kurtarailabilir

**Comment by merthankavak** [comment]
Geri dönüşleriniz için teşekkürler hocam. En kısa zamanda eksiklikleri gidereceğiz.
